import { Product, ProductCategory } from './types';

export const METABOLICS_AND_OTHERS: Product[] = [
  // --- BLENDS ---
  {
    id: 'KLOW',
    name: 'KLOW Blend (80mg total)',
    chemicalName: 'TB-500/BPC-157/GHK-Cu/KPV',
    casNumber: 'Mixture',
    formula: 'Complex',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 240.00,
    description: 'Research blend (TB 10mg + BPC 10mg + GHK 50mg + KPV 10mg). Supplied as a kit of 10 vials (80mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'BBG70',
    name: 'Glow Blend (70mg total)',
    chemicalName: 'TB-500/BPC-157/GHK-Cu',
    casNumber: 'Mixture',
    formula: 'Complex',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 227.00,
    description: 'Research blend (TB 10mg + BPC 10mg + GHK 50mg). Supplied as a kit of 10 vials (70mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'LC216',
    name: 'Lipo-C (10ml)',
    chemicalName: 'Methionine/Inositol/Choline',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.LIPOLYTICS,
    price: 80.00,
    description: 'Research lipolytic solution. Supplied as a kit of 10 vials (10ml each). Strictly for laboratory research use.',
    storage: '4°C',
    solubility: 'N/A',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'LB',
    name: 'Lemon Bottle (10ml)',
    chemicalName: 'Riboflavin/Bromelain/Lecithin',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.LIPOLYTICS,
    price: 72.00,
    description: 'Topical research solution. Supplied as a kit of 10 vials (10ml each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'N/A',
    analysisMethod: 'HPLC',
    inStock: true,
  },
    {
    id: 'BB10',
    name: 'BPC 5mg + TB 5mg Blend',
    chemicalName: 'BPC-157 / TB-500',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 117.00,
    description: 'Research blend. Supplied as a kit of 10 vials (10mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'BB20',
    name: 'BPC 10mg + TB 10mg Blend',
    chemicalName: 'BPC-157 / TB-500',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 196.00,
    description: 'Research blend. Supplied as a kit of 10 vials (20mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CS10',
    name: 'Cagri 5mg + Sema 5mg',
    chemicalName: 'Cagrilintide / Semaglutide',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 167.00,
    description: 'Research blend. Supplied as a kit of 10 vials (10mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CP10',
    name: 'CJC-1295 (No DAC) 5mg + IPA 5mg',
    chemicalName: 'Mod GRF / Ipamorelin',
    casNumber: 'Mixture',
    formula: 'Mixture',
    molecularWeight: 'Mixture',
    purity: 99.5,
    category: ProductCategory.BLENDS,
    price: 115.00,
    description: 'Research blend. Supplied as a kit of 10 vials (10mg total each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  // --- NAD+ / METABOLICS ---
  {
    id: 'NJ100',
    name: 'NAD+ 100mg',
    chemicalName: 'NAD+',
    casNumber: '53-84-9',
    formula: 'C21H27N7O14P2',
    molecularWeight: 663.43,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 45.00,
    description: 'Nicotinamide Adenine Dinucleotide. Supplied as a kit of 10 vials (100mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'NJ500',
    name: 'NAD+ 500mg',
    chemicalName: 'NAD+',
    casNumber: '53-84-9',
    formula: 'C21H27N7O14P2',
    molecularWeight: 663.43,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 90.00,
    description: 'Nicotinamide Adenine Dinucleotide. Supplied as a kit of 10 vials (500mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'NJ1000',
    name: 'NAD+ 1000mg',
    chemicalName: 'NAD+',
    casNumber: '53-84-9',
    formula: 'C21H27N7O14P2',
    molecularWeight: 663.43,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 169.00,
    description: 'Nicotinamide Adenine Dinucleotide. Supplied as a kit of 10 vials (1000mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'MS10',
    name: 'MOTS-C 10mg',
    chemicalName: 'MOTS-C',
    casNumber: '1627580-64-6',
    formula: 'C101H152N28O22S2',
    molecularWeight: 2174.6,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 68.00,
    description: 'Mitochondrial-derived peptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'MS40',
    name: 'MOTS-C 40mg',
    chemicalName: 'MOTS-C',
    casNumber: '1627580-64-6',
    formula: 'C101H152N28O22S2',
    molecularWeight: 2174.6,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 225.00,
    description: 'Mitochondrial-derived peptide. Supplied as a kit of 10 vials (40mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '2S10',
    name: 'SS-31 10mg',
    chemicalName: 'Elamipretide',
    casNumber: '736992-71-5',
    formula: 'C32H49N9O5',
    molecularWeight: 639.8,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 105.00,
    description: 'Mitochondria-targeted antioxidant. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '2S50',
    name: 'SS-31 50mg',
    chemicalName: 'Elamipretide',
    casNumber: '736992-71-5',
    formula: 'C32H49N9O5',
    molecularWeight: 639.8,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 410.00,
    description: 'Mitochondria-targeted antioxidant. Supplied as a kit of 10 vials (50mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '5AM',
    name: '5-amino-1MQ 5mg',
    chemicalName: '5-amino-1MQ',
    casNumber: '42464-96-0',
    formula: 'C10H11N2',
    molecularWeight: 159.2,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 89.00,
    description: 'NNMT inhibitor. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'LC600',
    name: 'L-Carnitine 600mg',
    chemicalName: 'L-Carnitine',
    casNumber: '541-15-1',
    formula: 'C7H15NO3',
    molecularWeight: 161.2,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 40.00,
    description: 'Metabolic reagent. Supplied as a kit of 10 vials (10ml each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'LC1200',
    name: 'L-Carnitine 1200mg',
    chemicalName: 'L-Carnitine',
    casNumber: '541-15-1',
    formula: 'C7H15NO3',
    molecularWeight: 161.2,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 50.00,
    description: 'Metabolic reagent. Supplied as a kit of 10 vials (10ml each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'AR50',
    name: 'AICAR 50mg',
    chemicalName: 'Acadesine',
    casNumber: '2627-69-2',
    formula: 'C9H14N4O5',
    molecularWeight: 258.2,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 60.00,
    description: 'AMPK activator. Supplied as a kit of 10 vials (50mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ARIM100',
    name: 'Arimidex 100mg',
    chemicalName: 'Anastrozole',
    casNumber: '120511-73-1',
    formula: 'C17H19N5',
    molecularWeight: 293.4,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 50.00,
    description: 'Aromatase inhibitor. Supplied as 20 capsules (100mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ARIM200',
    name: 'Arimidex 200mg',
    chemicalName: 'Anastrozole',
    casNumber: '120511-73-1',
    formula: 'C17H19N5',
    molecularWeight: 293.4,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 85.00,
    description: 'Aromatase inhibitor. Supplied as 20 capsules (200mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ARIM300',
    name: 'Arimidex 300mg',
    chemicalName: 'Anastrozole',
    casNumber: '120511-73-1',
    formula: 'C17H19N5',
    molecularWeight: 293.4,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 120.00,
    description: 'Aromatase inhibitor. Supplied as 20 capsules (300mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ARIM500',
    name: 'Arimidex 500mg',
    chemicalName: 'Anastrozole',
    casNumber: '120511-73-1',
    formula: 'C17H19N5',
    molecularWeight: 293.4,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 180.00,
    description: 'Aromatase inhibitor. Supplied as 20 capsules (500mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ARIM1000',
    name: 'Arimidex 1000mg',
    chemicalName: 'Anastrozole',
    casNumber: '120511-73-1',
    formula: 'C17H19N5',
    molecularWeight: 293.4,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 320.00,
    description: 'Aromatase inhibitor. Supplied as 20 capsules (1000mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'DMSO',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'GTT600',
    name: 'Glutathione 600mg',
    chemicalName: 'L-Glutathione',
    casNumber: '70-18-8',
    formula: 'C10H17N3O6S',
    molecularWeight: 307.3,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 59.00,
    description: 'Antioxidant reagent. Supplied as a kit of 10 vials (600mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'GTT',
    name: 'Glutathione 1500mg',
    chemicalName: 'L-Glutathione',
    casNumber: '70-18-8',
    formula: 'C10H17N3O6S',
    molecularWeight: 307.3,
    purity: 99.5,
    category: ProductCategory.METABOLICS,
    price: 89.00,
    description: 'Antioxidant reagent. Supplied as a kit of 10 vials (1500mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'WA3',
    name: 'Bac Water 3ml',
    chemicalName: 'Bacteriostatic Water',
    casNumber: 'N/A',
    formula: 'H2O + Benzyl Alcohol',
    molecularWeight: 18.0,
    purity: 99.5,
    category: ProductCategory.SOLVENTS,
    price: 10.00,
    description: 'Reconstitution solvent. Supplied as a kit of 10 vials (3ml each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'N/A',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'WA10',
    name: 'Bac Water 10ml',
    chemicalName: 'Bacteriostatic Water',
    casNumber: 'N/A',
    formula: 'H2O + Benzyl Alcohol',
    molecularWeight: 18.0,
    purity: 99.5,
    category: ProductCategory.SOLVENTS,
    price: 11.00,
    description: 'Reconstitution solvent. Supplied as a kit of 10 vials (10ml each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'N/A',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'P41',
    name: 'PT-141 10mg',
    chemicalName: 'Bremelanotide',
    casNumber: '189691-06-3',
    formula: 'C50H68N14O10',
    molecularWeight: 1025.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 65.00,
    description: 'Melanocortin agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '5AD',
    name: 'AOD9604 5mg',
    chemicalName: 'AOD9604',
    casNumber: '221231-10-3',
    formula: 'C78H123N23O23S2',
    molecularWeight: 1815.1,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 101.00,
    description: 'HGH Fragment. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '10AD',
    name: 'AOD9604 10mg',
    chemicalName: 'AOD9604',
    casNumber: '221231-10-3',
    formula: 'C78H123N23O23S2',
    molecularWeight: 1815.1,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 185.00,
    description: 'HGH Fragment. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CU',
    name: 'GHK-Cu 50mg',
    chemicalName: 'GHK-Cu',
    casNumber: '49557-75-7',
    formula: 'C14H24N6O4Cu',
    molecularWeight: 403.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 33.00,
    description: 'Copper peptide. Supplied as a kit of 10 vials (50mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CU100',
    name: 'GHK-Cu 100mg',
    chemicalName: 'GHK-Cu',
    casNumber: '49557-75-7',
    formula: 'C14H24N6O4Cu',
    molecularWeight: 403.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 59.00,
    description: 'Copper peptide. Supplied as a kit of 10 vials (100mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'H10',
    name: 'HGH 10IU',
    chemicalName: 'Somatropin',
    casNumber: '12629-01-5',
    formula: 'C990H1529N263O299S7',
    molecularWeight: 22124,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 49.00,
    description: 'Recombinant growth hormone. Supplied as a kit of 10 vials (10IU each). Strictly for laboratory research use.',
    storage: '4°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'H15',
    name: 'HGH 15IU',
    chemicalName: 'Somatropin',
    casNumber: '12629-01-5',
    formula: 'C990H1529N263O299S7',
    molecularWeight: 22124,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 73.00,
    description: 'Recombinant growth hormone. Supplied as a kit of 10 vials (15IU each). Strictly for laboratory research use.',
    storage: '4°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CND2',
    name: 'CJC-1295 (No DAC) 2mg',
    chemicalName: 'Mod GRF 1-29',
    casNumber: '863288-34-0',
    formula: 'C152H252N44O42',
    molecularWeight: 3367.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 41.00,
    description: 'GHRH analog. Supplied as a kit of 10 vials (2mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CND5',
    name: 'CJC-1295 (No DAC) 5mg',
    chemicalName: 'Mod GRF 1-29',
    casNumber: '863288-34-0',
    formula: 'C152H252N44O42',
    molecularWeight: 3367.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 95.00,
    description: 'GHRH analog. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CND10',
    name: 'CJC-1295 (No DAC) 10mg',
    chemicalName: 'Mod GRF 1-29',
    casNumber: '863288-34-0',
    formula: 'C152H252N44O42',
    molecularWeight: 3367.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 185.00,
    description: 'GHRH analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CD2',
    name: 'CJC-1295 (With DAC) 2mg',
    chemicalName: 'CJC-1295 DAC',
    casNumber: '863288-34-0',
    formula: 'Complex',
    molecularWeight: 3647.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 72.00,
    description: 'Long-acting GHRH. Supplied as a kit of 10 vials (2mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CD5',
    name: 'CJC-1295 (With DAC) 5mg',
    chemicalName: 'CJC-1295 DAC',
    casNumber: '863288-34-0',
    formula: 'Complex',
    molecularWeight: 3647.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 172.00,
    description: 'Long-acting GHRH. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'MT1',
    name: 'Melanotan I 10mg',
    chemicalName: 'Afamelanotide',
    casNumber: '75921-69-6',
    formula: 'C78H111N21O19',
    molecularWeight: 1646.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 62.00,
    description: 'MC1R agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ML10',
    name: 'Melanotan II 10mg',
    chemicalName: 'Melanotan II',
    casNumber: '121062-08-6',
    formula: 'C50H69N15O9',
    molecularWeight: 1024.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 62.00,
    description: 'MC agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'KP10',
    name: 'KPV 10mg',
    chemicalName: 'KPV',
    casNumber: '67763-96-6',
    formula: 'C16H31N5O4',
    molecularWeight: 357.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 69.00,
    description: 'Alpha-MSH fragment. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SMO5',
    name: 'Sermorelin 5mg',
    chemicalName: 'Sermorelin',
    casNumber: '86168-78-7',
    formula: 'C149H246N44O42S',
    molecularWeight: 3357.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 70.00,
    description: 'GHRH 1-29. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SMO10',
    name: 'Sermorelin 10mg',
    chemicalName: 'Sermorelin',
    casNumber: '86168-78-7',
    formula: 'C149H246N44O42S',
    molecularWeight: 3357.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 142.00,
    description: 'GHRH 1-29. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TSM5',
    name: 'Tesamorelin 5mg',
    chemicalName: 'Tesamorelin',
    casNumber: '218949-48-5',
    formula: 'C221H366N72O67S',
    molecularWeight: 5135.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 112.00,
    description: 'GHRH analog. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TSM10',
    name: 'Tesamorelin 10mg',
    chemicalName: 'Tesamorelin',
    casNumber: '218949-48-5',
    formula: 'C221H366N72O67S',
    molecularWeight: 5135.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 220.00,
    description: 'GHRH analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'IG01',
    name: 'IGF-1 LR3 0.1mg',
    chemicalName: 'Long R3 IGF-1',
    casNumber: '946870-92-4',
    formula: 'C400H625N111O115S9',
    molecularWeight: 9111.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 45.00,
    description: 'Insulin-like Growth Factor analog. Supplied as a kit of 10 vials (0.1mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'IG1',
    name: 'IGF-1 LR3 1mg',
    chemicalName: 'Long R3 IGF-1',
    casNumber: '946870-92-4',
    formula: 'C400H625N111O115S9',
    molecularWeight: 9111.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 220.00,
    description: 'Insulin-like Growth Factor analog. Supplied as a kit of 10 vials (1mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ET10',
    name: 'Epitalon 10mg',
    chemicalName: 'Epithalon',
    casNumber: '307297-39-8',
    formula: 'C14H22N4O9',
    molecularWeight: 390.4,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 35.00,
    description: 'Telomerase activator. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'ET50',
    name: 'Epitalon 50mg',
    chemicalName: 'Epithalon',
    casNumber: '307297-39-8',
    formula: 'C14H22N4O9',
    molecularWeight: 390.4,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 162.00,
    description: 'Telomerase activator. Supplied as a kit of 10 vials (50mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'G75',
    name: 'HMG 75IU',
    chemicalName: 'Human Menopausal Gonadotropin',
    casNumber: '61489-71-2',
    formula: 'Complex',
    molecularWeight: 'Complex',
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 62.00,
    description: 'FSH/LH mixture. Supplied as a kit of 10 vials (75IU each). Strictly for laboratory research use.',
    storage: '4°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'MDT10',
    name: 'Mazdutide 10mg',
    chemicalName: 'Mazdutide',
    casNumber: '2478385-80-5',
    formula: 'Research Seq',
    molecularWeight: 4800.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 195.00,
    description: 'OXM analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SUR10',
    name: 'Survodutide 10mg',
    chemicalName: 'Survodutide',
    casNumber: '2607758-75-6',
    formula: 'Research Seq',
    molecularWeight: 4900.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 296.00,
    description: 'Glucagon/GLP-1 agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'IP5',
    name: 'Ipamorelin 5mg',
    chemicalName: 'Ipamorelin',
    casNumber: '170851-70-4',
    formula: 'C38H49N9O5',
    molecularWeight: 711.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 38.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'IP10',
    name: 'Ipamorelin 10mg',
    chemicalName: 'Ipamorelin',
    casNumber: '170851-70-4',
    formula: 'C38H49N9O5',
    molecularWeight: 711.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 72.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'AP5',
    name: 'Adipotide 5mg',
    chemicalName: 'Adipotide',
    casNumber: 'N/A',
    formula: 'Complex',
    molecularWeight: 2555.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 140.00,
    description: 'Peptidomimetic. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'XA5',
    name: 'Semax 5mg',
    chemicalName: 'Semax',
    casNumber: '80714-61-0',
    formula: 'C37H51N9O10S',
    molecularWeight: 813.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 44.00,
    description: 'ACTH analog. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'XA10',
    name: 'Semax 10mg',
    chemicalName: 'Semax',
    casNumber: '80714-61-0',
    formula: 'C37H51N9O10S',
    molecularWeight: 813.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 72.00,
    description: 'ACTH analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'RA10',
    name: 'ARA-290 10mg',
    chemicalName: 'Cibinetide',
    casNumber: '1208243-50-8',
    formula: 'C51H84N16O21',
    molecularWeight: 1257.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 72.00,
    description: 'EPO derivative. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'DS5',
    name: 'DSIP 5mg',
    chemicalName: 'DSIP',
    casNumber: '62568-57-4',
    formula: 'C35H48N10O15',
    molecularWeight: 848.8,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 40.00,
    description: 'Neuropeptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'DS10',
    name: 'DSIP 10mg',
    chemicalName: 'DSIP',
    casNumber: '62568-57-4',
    formula: 'C35H48N10O15',
    molecularWeight: 848.8,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 82.00,
    description: 'Neuropeptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'HX5',
    name: 'Hexarelin Acetate 5mg',
    chemicalName: 'Hexarelin',
    casNumber: '140703-51-1',
    formula: 'C47H58N12O6',
    molecularWeight: 887.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 87.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'KS5',
    name: 'Kisspeptin-10 5mg',
    chemicalName: 'Kisspeptin',
    casNumber: '374675-21-5',
    formula: 'C63H83N15O18',
    molecularWeight: 1302.4,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 60.00,
    description: 'Metastin fragment. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'KS10',
    name: 'Kisspeptin-10 10mg',
    chemicalName: 'Kisspeptin',
    casNumber: '374675-21-5',
    formula: 'C63H83N15O18',
    molecularWeight: 1302.4,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 117.00,
    description: 'Metastin fragment. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'OT2',
    name: 'Oxytocin Acetate 2mg',
    chemicalName: 'Oxytocin',
    casNumber: '50-56-6',
    formula: 'C43H66N12O12S2',
    molecularWeight: 1007.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 36.00,
    description: 'Neuropeptide. Supplied as a kit of 10 vials (2mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'OT5',
    name: 'Oxytocin Acetate 5mg',
    chemicalName: 'Oxytocin',
    casNumber: '50-56-6',
    formula: 'C43H66N12O12S2',
    molecularWeight: 1007.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 62.00,
    description: 'Neuropeptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SK5',
    name: 'Selank 5mg',
    chemicalName: 'Selank',
    casNumber: '129954-34-3',
    formula: 'C33H57N11O9',
    molecularWeight: 751.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 45.00,
    description: 'Tuftsin analog. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SK10',
    name: 'Selank 10mg',
    chemicalName: 'Selank',
    casNumber: '129954-34-3',
    formula: 'C33H57N11O9',
    molecularWeight: 751.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 72.00,
    description: 'Tuftsin analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TA5',
    name: 'Thymosin Alpha-1 5mg',
    chemicalName: 'Thymalfasin',
    casNumber: '62304-98-7',
    formula: 'C129H215N33O55',
    molecularWeight: 3108.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 100.00,
    description: 'Thymic peptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TA10',
    name: 'Thymosin Alpha-1 10mg',
    chemicalName: 'Thymalfasin',
    casNumber: '62304-98-7',
    formula: 'C129H215N33O55',
    molecularWeight: 3108.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 168.00,
    description: 'Thymic peptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TY10',
    name: 'Thymalin 10mg',
    chemicalName: 'Thymalin',
    casNumber: '79621-14-0',
    formula: 'Complex',
    molecularWeight: 'Complex',
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 63.00,
    description: 'Bioregulator. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'G25',
    name: 'GHRP-2 Acetate 5mg',
    chemicalName: 'Pralmorelin',
    casNumber: '158861-67-7',
    formula: 'C45H55N9O6',
    molecularWeight: 817.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 27.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'G210',
    name: 'GHRP-2 Acetate 10mg',
    chemicalName: 'Pralmorelin',
    casNumber: '158861-67-7',
    formula: 'C45H55N9O6',
    molecularWeight: 817.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 54.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'G65',
    name: 'GHRP-6 Acetate 5mg',
    chemicalName: 'GHRP-6',
    casNumber: '87616-84-0',
    formula: 'C46H56N12O6',
    molecularWeight: 873.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 27.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'G610',
    name: 'GHRP-6 Acetate 10mg',
    chemicalName: 'GHRP-6',
    casNumber: '87616-84-0',
    formula: 'C46H56N12O6',
    molecularWeight: 873.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 54.00,
    description: 'GH secretagogue. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'DR5',
    name: 'Dermorphin 5mg',
    chemicalName: 'Dermorphin',
    casNumber: '77614-16-5',
    formula: 'C40H50N8O10',
    molecularWeight: 802.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 36.00,
    description: 'Opioid peptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'NP810',
    name: 'Snap-8 10mg',
    chemicalName: 'Acetyl Octapeptide-3',
    casNumber: '868844-74-0',
    formula: 'C41H70N16O16S',
    molecularWeight: 1075.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 41.00,
    description: 'Argireline analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: '375',
    name: 'LL-37 5mg',
    chemicalName: 'LL-37',
    casNumber: '154947-66-7',
    formula: 'C205H340N60O53',
    molecularWeight: 4493.3,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 90.00,
    description: 'Antimicrobial peptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'VP10',
    name: 'VIP 10mg',
    chemicalName: 'Vasoactive Intestinal Peptide',
    casNumber: '37221-79-7',
    formula: 'C147H238N44O42S',
    molecularWeight: 3325.8,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 178.00,
    description: 'Neuropeptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'F410',
    name: 'FOXO4 10mg',
    chemicalName: 'FOXO4-DRI',
    casNumber: 'N/A',
    formula: 'Research Seq',
    molecularWeight: 5358.0,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 360.00,
    description: 'Senolytic peptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'FM2',
    name: 'MGF 2mg',
    chemicalName: 'MGF',
    casNumber: 'N/A',
    formula: 'Research Seq',
    molecularWeight: 2868.2,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 62.00,
    description: 'IGF-1 splice variant. Supplied as a kit of 10 vials (2mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'FMP2',
    name: 'PEG-MGF 2mg',
    chemicalName: 'PEG-MGF',
    casNumber: 'N/A',
    formula: 'Complex',
    molecularWeight: 'Complex',
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 90.00,
    description: 'Pegylated MGF. Supplied as a kit of 10 vials (2mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'MK75',
    name: 'MK-677 5mg',
    chemicalName: 'Ibutamoren',
    casNumber: '159752-10-0',
    formula: 'C27H36N4O5S',
    molecularWeight: 528.7,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 22.00,
    description: 'Non-peptide ghrelin agonist. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: 'Room Temp',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  }
];