import { Product, ProductCategory } from './types';

export const PEPTIDES_LIST: Product[] = [
  // --- TIRZEPATIDE ---
  {
    id: 'TR5',
    name: 'Tirzepatide 5mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 49.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (5mg each). Strictly for in vitro research regarding insulin secretion pathways.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TR10',
    name: 'Tirzepatide 10mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 67.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TR15',
    name: 'Tirzepatide 15mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 83.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (15mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TR20',
    name: 'Tirzepatide 20mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 110.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (20mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TR30',
    name: 'Tirzepatide 30mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 155.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (30mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'TR60',
    name: 'Tirzepatide 60mg',
    chemicalName: 'Tirzepatide',
    casNumber: '2023788-19-2',
    formula: 'C225H348N48O68',
    molecularWeight: 4813.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 232.00,
    description: 'Dual GIP/GLP-1 receptor agonist. Supplied as a kit of 10 vials (60mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  // --- SEMAGLUTIDE ---
  {
    id: 'SM5',
    name: 'Semaglutide 5mg',
    chemicalName: 'Semaglutide',
    casNumber: '910463-68-2',
    formula: 'C187H291N45O59',
    molecularWeight: 4113.58,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 42.00,
    description: 'GLP-1 receptor agonist. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SM10',
    name: 'Semaglutide 10mg',
    chemicalName: 'Semaglutide',
    casNumber: '910463-68-2',
    formula: 'C187H291N45O59',
    molecularWeight: 4113.58,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 60.00,
    description: 'GLP-1 receptor agonist. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SM15',
    name: 'Semaglutide 15mg',
    chemicalName: 'Semaglutide',
    casNumber: '910463-68-2',
    formula: 'C187H291N45O59',
    molecularWeight: 4113.58,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 81.00,
    description: 'GLP-1 receptor agonist. Supplied as a kit of 10 vials (15mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'SM20',
    name: 'Semaglutide 20mg',
    chemicalName: 'Semaglutide',
    casNumber: '910463-68-2',
    formula: 'C187H291N45O59',
    molecularWeight: 4113.58,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 90.00,
    description: 'GLP-1 receptor agonist. Supplied as a kit of 10 vials (20mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  // --- RETATRUTIDE ---
  {
    id: 'RT5',
    name: 'Retatrutide 5mg',
    chemicalName: 'Retatrutide',
    casNumber: '2381089-83-2',
    formula: 'Research Seq',
    molecularWeight: 4731.33,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 91.00,
    description: 'Tri-agonist (GLP-1/GIP/GCGR). Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'RT10',
    name: 'Retatrutide 10mg',
    chemicalName: 'Retatrutide',
    casNumber: '2381089-83-2',
    formula: 'Research Seq',
    molecularWeight: 4731.33,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 130.00,
    description: 'Tri-agonist (GLP-1/GIP/GCGR). Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'RT20',
    name: 'Retatrutide 20mg',
    chemicalName: 'Retatrutide',
    casNumber: '2381089-83-2',
    formula: 'Research Seq',
    molecularWeight: 4731.33,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 207.00,
    description: 'Tri-agonist (GLP-1/GIP/GCGR). Supplied as a kit of 10 vials (20mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'RT30',
    name: 'Retatrutide 30mg',
    chemicalName: 'Retatrutide',
    casNumber: '2381089-83-2',
    formula: 'Research Seq',
    molecularWeight: 4731.33,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 270.00,
    description: 'Tri-agonist (GLP-1/GIP/GCGR). Supplied as a kit of 10 vials (30mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
    // --- CAGRILINTIDE ---
  {
    id: 'CGL5',
    name: 'Cagrilintide 5mg',
    chemicalName: 'Cagrilintide',
    casNumber: '1415456-99-3',
    formula: 'C189H287N53O56',
    molecularWeight: 4425.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 117.00,
    description: 'Long-acting amylin analog. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'CGL10',
    name: 'Cagrilintide 10mg',
    chemicalName: 'Cagrilintide',
    casNumber: '1415456-99-3',
    formula: 'C189H287N53O56',
    molecularWeight: 4425.9,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 227.00,
    description: 'Long-acting amylin analog. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
    // --- TB / BPC ---
  {
    id: 'BT5',
    name: 'TB-500 5mg',
    chemicalName: 'Thymosin Beta-4',
    casNumber: '77591-33-4',
    formula: 'C212H350N56O78S',
    molecularWeight: 4963.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 89.00,
    description: 'Thymosin Beta-4 fragment. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'BT10',
    name: 'TB-500 10mg',
    chemicalName: 'Thymosin Beta-4',
    casNumber: '77591-33-4',
    formula: 'C212H350N56O78S',
    molecularWeight: 4963.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 168.00,
    description: 'Thymosin Beta-4 fragment. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'BC5',
    name: 'BPC-157 5mg',
    chemicalName: 'BPC-157',
    casNumber: '137525-51-0',
    formula: 'C62H98N16O22',
    molecularWeight: 1419.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 48.00,
    description: 'Pentadecapeptide. Supplied as a kit of 10 vials (5mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
  {
    id: 'BC10',
    name: 'BPC-157 10mg',
    chemicalName: 'BPC-157',
    casNumber: '137525-51-0',
    formula: 'C62H98N16O22',
    molecularWeight: 1419.5,
    purity: 99.5,
    category: ProductCategory.PEPTIDES,
    price: 70.00,
    description: 'Pentadecapeptide. Supplied as a kit of 10 vials (10mg each). Strictly for laboratory research use.',
    storage: '-20°C',
    solubility: 'Water',
    analysisMethod: 'HPLC',
    inStock: true,
  },
];